# Generated by Django 5.2.1 on 2025-05-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shorturls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="shorturlclick",
            name="short_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shorturls.shorturl"
            ),
        ),
    ]
