# Generated by Django 5.2.1 on 2025-06-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shorturls", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="name",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
