# Generated by Django 5.2.1 on 2025-09-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fingerprint", "0001_initial"),
        ("shorturls", "0003_shorturl_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturlclick",
            name="fingerprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="fingerprint.fingerprint",
            ),
        ),
    ]
