# Generated by Django 5.2.1 on 2025-09-07 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shorturls", "0004_shorturlclick_fingerprint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shorturlclick",
            name="device_type",
        ),
        migrations.RemoveField(
            model_name="shorturlclick",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="shorturlclick",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="shorturlclick",
            name="user_agent",
        ),
    ]
