# Generated by Django 5.2.1 on 2025-10-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0005_remove_shorturlclick_device_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'permissions': [('view_shorturl_analytics', 'View Short URL analytics')]},
        ),
    ]
