# Generated by Django 5.2.1 on 2025-11-27 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0004_alter_fingerprint_user_agent'),
        ('shorturls', '0006_alter_shorturl_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['user', '-created_at'], name='shorturl_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='shorturl_code_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturlclick',
            index=models.Index(fields=['short_url', '-clicked_at'], name='click_url_time_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturlclick',
            index=models.Index(fields=['fingerprint'], name='click_fingerprint_idx'),
        ),
    ]
