# Generated by Django 5.2.1 on 2025-11-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest_user',
            field=models.BooleanField(default=False),
        ),
    ]
