# Generated by Django 5.2.1 on 2025-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fingerprint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fingerprint",
            name="browser_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="browser_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="device_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="os",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="referrer",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
