# Generated by Django 5.2.1 on 2025-09-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fingerprint", "0003_fingerprint_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fingerprint",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
